package com.terralite.tools.scripting;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ScriptApiMarkdownGeneratorTest {
    @TempDir
    Path tempDir;

    @Test
    void writesScriptingApiDocumentation() throws Exception {
        Path output = tempDir.resolve("scripting-api.md");

        ScriptApiMarkdownGenerator.generate(output);

        String markdown = Files.readString(output);
        assertTrue(markdown.contains("# Terralite Scripting API"));
        assertTrue(markdown.contains("Generated by `:tools:generateScriptingApiDocs`"));
        assertTrue(markdown.contains("### `ServerWorldApi`"));
        assertTrue(markdown.contains("`loadChunk(x: number, y: number, z: number): boolean`"));
        assertTrue(markdown.contains("### `BlockBuilder`"));
        assertTrue(markdown.contains("type ResourceId = `${string}:${string}`;"));
    }

    @Test
    void checkPassesWhenDocumentationMatches() throws Exception {
        Path output = tempDir.resolve("scripting-api.md");
        ScriptApiMarkdownGenerator.generate(output);

        ScriptApiMarkdownGenerator.check(output);
    }

    @Test
    void staleCheckMessageMentionsUnixAndWindowsCommands() throws Exception {
        Path output = tempDir.resolve("scripting-api.md");
        Files.writeString(output, "stale");

        IllegalStateException exception = assertThrows(IllegalStateException.class,
                () -> ScriptApiMarkdownGenerator.check(output));

        assertTrue(exception.getMessage().contains("./gradlew :tools:generateScriptingApiDocs"));
        assertTrue(exception.getMessage().contains(".\\gradlew.bat :tools:generateScriptingApiDocs"));
    }
}
