// Generated by :tools:generateTypeScriptApi.
// Provides editor types for Terralite JavaScript content scripts.

type ResourceId = `${string}:${string}`;

declare const api: ScriptRuntimeApi;
declare const StartupEvents: StartupEventsApi;
declare const Registry: RegistryApi;

interface ScriptRuntimeApi {
  info(message: string): void;
  onTick(handler: (tick: ServerTick) => void): void;
  world(): ServerWorldApi;
}

interface ServerTick {
  readonly index: number;
  readonly deltaMillis: number;
  readonly totalMillis: number;
}

interface ServerWorldApi {
  entityCount(): number;
  chunkCount(): number;
  hasChunk(x: number, y: number, z: number): boolean;
  loadChunk(x: number, y: number, z: number): void;
  unloadChunk(x: number, y: number, z: number): void;
}

interface StartupEventsApi {
  registry(type: 'block', handler: (event: BlockRegistryEvent) => void): void;
  registry(type: 'item', handler: (event: ItemRegistryEvent) => void): void;
  registry(type: 'biome', handler: (event: BiomeRegistryEvent) => void): void;
  registry(type: 'tag', handler: (event: TagRegistryEvent) => void): void;
  registry(type: 'creative_category', handler: (event: CreativeCategoryRegistryEvent) => void): void;
}

interface BlockRegistryEvent {
  create(id: ResourceId): BlockBuilder;
}

interface ItemRegistryEvent {
  create(id: ResourceId): ItemBuilder;
}

interface BiomeRegistryEvent {
  create(id: ResourceId): BiomeBuilder;
}

interface TagRegistryEvent {
  create(id: ResourceId): TagBuilder;
}

interface CreativeCategoryRegistryEvent {
  create(id: ResourceId): CreativeCategoryBuilder;
}

interface BlockBuilder {
  displayName(value: string): this;
  solid(value: boolean): this;
  translucent(value: boolean): this;
  material(value: string): this;
  hardness(value: number): this;
  resistance(value: number): this;
  requiresTool(value: boolean): this;
  soundType(value: string): this;
  category(id: ResourceId): this;
  tag(id: ResourceId): this;
  model(path: string): this;
  texture(path: string): this;
  renderType(type: string): this;
  color(r: number, g: number, b: number): this;
  opacity(value: number): this;
  tintKey(value: boolean): this;
  drops(value: unknown): this;
  property(key: string, value: unknown): this;
  states(value: unknown): this;
  variants(value: unknown): this;
}

interface ItemBuilder {
  displayName(value: string): this;
  stackSize(value: number): this;
  weight(value: number): this;
  placesBlock(id: ResourceId): this;
  category(id: ResourceId): this;
  tag(id: ResourceId): this;
  icon(path: string): this;
}

interface BiomeBuilder {
  name(value: string): this;
  priority(value: number): this;
  rarity(value: number): this;
  temperature(min: number, max: number): this;
  humidity(min: number, max: number): this;
  terrain(baseHeight: number, heightVariation: number): this;
  surfaceTop(id: ResourceId): this;
  surfaceMiddle(id: ResourceId): this;
  surfaceMiddleDepth(depth: number): this;
  surfaceBase(id: ResourceId): this;
}

interface TagBuilder {
  description(value: string): this;
  member(id: ResourceId): this;
}

interface CreativeCategoryBuilder {
  title(value: string): this;
  icon(id: ResourceId): this;
  entry(id: ResourceId): this;
}

interface RegistryApi {
  getBlock(id: ResourceId): unknown;
  getItem(id: ResourceId): unknown;
  getBiome(id: ResourceId): unknown;
  modifyBlock(id: ResourceId, handler: (block: BlockModifier) => void): void;
}

interface BlockModifier {
  displayName: string;
  hardness: number;
  resistance: number;
  solid: boolean;
  transparent: boolean;
  requiresTool: boolean;
  material: string;
  soundType: string;
}
