// Generated by :tools:generateTypeScriptApi.
// Provides editor types for Terralite JavaScript content scripts.

/**
 * Namespaced Terralite resource id, such as `terralite:block/stone`.
 */
type ResourceId = `${string}:${string}`;

/**
 * Runtime API available to server-side scripts.
 */
declare const api: ScriptRuntimeApi;

/**
 * Startup-only event API used to register content before game data freezes.
 */
declare const StartupEvents: StartupEventsApi;

/**
 * Startup-only registry API used to inspect or mutate content before freeze.
 */
declare const Registry: RegistryApi;

interface ScriptRuntimeApi {
  /** Record an informational script diagnostic. */
  info(message: string): void;
  /** Run a handler once per authoritative server tick. */
  onTick(handler: (tick: ServerTick) => void): void;
  /** Access world operations exposed to server scripts. */
  world(): ServerWorldApi;
}

interface ServerTick {
  /** Monotonic tick index. */
  readonly index: number;
  /** Milliseconds elapsed during this tick. */
  readonly deltaMillis: number;
  /** Milliseconds elapsed since the server script host started. */
  readonly totalMillis: number;
}

interface ServerWorldApi {
  /** Number of entities currently known to the script world view. */
  entityCount(): number;
  /** Number of loaded chunks currently known to the script world view. */
  chunkCount(): number;
  /** Returns true when the chunk at the given chunk coordinates is loaded. */
  hasChunk(x: number, y: number, z: number): boolean;
  /** Load or create the chunk at the given chunk coordinates. */
  loadChunk(x: number, y: number, z: number): boolean;
  /** Unload the chunk at the given chunk coordinates. */
  unloadChunk(x: number, y: number, z: number): boolean;
}

interface StartupEventsApi {
  /** Register or modify block content during startup. */
  registry(type: 'block', handler: (event: BlockRegistryEvent) => void): void;
  /** Register or modify item content during startup. */
  registry(type: 'item', handler: (event: ItemRegistryEvent) => void): void;
  /** Register or modify biome content during startup. */
  registry(type: 'biome', handler: (event: BiomeRegistryEvent) => void): void;
  /** Register or modify tag content during startup. */
  registry(type: 'tag', handler: (event: TagRegistryEvent) => void): void;
  /** Register or modify creative category content during startup. */
  registry(type: 'creative_category', handler: (event: CreativeCategoryRegistryEvent) => void): void;
}

interface BlockRegistryEvent {
  /** Create a block with the given resource id. */
  create(id: ResourceId): BlockBuilder;
}

interface ItemRegistryEvent {
  /** Create an item with the given resource id. */
  create(id: ResourceId): ItemBuilder;
}

interface BiomeRegistryEvent {
  /** Create a biome with the given resource id. */
  create(id: ResourceId): BiomeBuilder;
}

interface TagRegistryEvent {
  /** Create a tag with the given resource id. */
  create(id: ResourceId): TagBuilder;
}

interface CreativeCategoryRegistryEvent {
  /** Create a creative category with the given resource id. */
  create(id: ResourceId): CreativeCategoryBuilder;
}

interface BlockBuilder {
  /** Set the player-facing block name. */
  displayName(value: string): this;
  /** Set whether this block has full solid collision. */
  solid(value: boolean): this;
  /** Set whether this block should be treated as transparent. */
  translucent(value: boolean): this;
  /** Set the block material key, such as `stone`, `dirt`, or `plant`. */
  material(value: string): this;
  /** Set break hardness; must be non-negative when content is built. */
  hardness(value: number): this;
  /** Set explosion resistance; must be non-negative when content is built. */
  resistance(value: number): this;
  /** Set whether the block requires an appropriate tool. */
  requiresTool(value: boolean): this;
  /** Set the sound type key. */
  soundType(value: string): this;
  /** Add this block to a creative category. */
  category(id: ResourceId): this;
  /** Add this block as a member of a tag. */
  tag(id: ResourceId): this;
  /** Placeholder for future block model path support. Currently chainable only. */
  model(path: string): this;
  /** Placeholder for future block texture path support. Currently chainable only. */
  texture(path: string): this;
  /** Placeholder for future block render type support. Currently chainable only. */
  renderType(type: string): this;
  /** Placeholder for future block color support. Currently chainable only. */
  color(r: number, g: number, b: number): this;
  /** Placeholder for future block opacity support. Currently chainable only. */
  opacity(value: number): this;
  /** Placeholder for future tint support. Currently chainable only. */
  tintKey(value: boolean): this;
  /** Placeholder for future drop table support. Currently chainable only. */
  drops(value: unknown): this;
  /** Placeholder for future custom block properties. Currently chainable only. */
  property(key: string, value: unknown): this;
  /** Placeholder for future block state definitions. Currently chainable only. */
  states(value: unknown): this;
  /** Placeholder for future block variant definitions. Currently chainable only. */
  variants(value: unknown): this;
}

interface ItemBuilder {
  /** Set the player-facing item name. */
  displayName(value: string): this;
  /** Set maximum stack size. */
  stackSize(value: number): this;
  /** Set item weight for future inventory/balance systems. */
  weight(value: number): this;
  /** Set the block this item places. */
  placesBlock(id: ResourceId): this;
  /** Add this item to a creative category. */
  category(id: ResourceId): this;
  /** Add this item as a member of a tag. */
  tag(id: ResourceId): this;
  /** Placeholder for future item icon path support. Currently chainable only. */
  icon(path: string): this;
}

interface BiomeBuilder {
  /** Set the player-facing biome name. */
  name(value: string): this;
  /** Set biome selection priority. */
  priority(value: number): this;
  /** Set biome rarity weighting. */
  rarity(value: number): this;
  /** Set inclusive temperature range for biome selection. */
  temperature(min: number, max: number): this;
  /** Set inclusive humidity range for biome selection. */
  humidity(min: number, max: number): this;
  /** Set base terrain height and variation. */
  terrain(baseHeight: number, heightVariation: number): this;
  /** Set the top surface block id. */
  surfaceTop(id: ResourceId): this;
  /** Set the middle surface block id. */
  surfaceMiddle(id: ResourceId): this;
  /** Set the depth of the middle surface layer. */
  surfaceMiddleDepth(depth: number): this;
  /** Set the base surface block id. */
  surfaceBase(id: ResourceId): this;
}

interface TagBuilder {
  /** Set the tag description. */
  description(value: string): this;
  /** Add a block or item member id. */
  member(id: ResourceId): this;
}

interface CreativeCategoryBuilder {
  /** Set the player-facing category title. */
  title(value: string): this;
  /** Set the block or item id used as the category icon. */
  icon(id: ResourceId): this;
  /** Add a block or item id to the category ordering. */
  entry(id: ResourceId): this;
}

interface RegistryApi {
  /** Get a startup-registered block by id. */
  getBlock(id: ResourceId): unknown;
  /** Get a startup-registered item by id. */
  getItem(id: ResourceId): unknown;
  /** Get a startup-registered biome by id. */
  getBiome(id: ResourceId): unknown;
  /** Modify a registered block before registries freeze. */
  modifyBlock(id: ResourceId, handler: (block: BlockModifier) => void): void;
}

interface BlockModifier {
  /** Player-facing block name. */
  displayName: string;
  /** Break hardness. */
  hardness: number;
  /** Explosion resistance. */
  resistance: number;
  /** Whether this block has full solid collision. */
  solid: boolean;
  /** Whether this block should be treated as transparent. */
  transparent: boolean;
  /** Whether this block requires an appropriate tool. */
  requiresTool: boolean;
  /** Block material key. */
  material: string;
  /** Block sound type key. */
  soundType: string;
}

