package com.terralite.game.scripting;

import com.terralite.core.registry.MutableRegistry;
import com.terralite.core.registry.ResourceId;
import com.terralite.game.biome.Biome;
import com.terralite.game.block.Block;
import com.terralite.game.category.CreativeCategory;
import com.terralite.game.item.Item;
import com.terralite.game.tag.Tag;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.Function;
import org.mozilla.javascript.Scriptable;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public final class StartupEventsScriptApi {
    private final MutableRegistry<Block> blockRegistry;
    private final MutableRegistry<Item> itemRegistry;
    private final MutableRegistry<Biome> biomeRegistry;
    private final MutableRegistry<Tag> tagRegistry;
    private final MutableRegistry<CreativeCategory> creativeCategoryRegistry;

    public StartupEventsScriptApi(
            MutableRegistry<Block> blockRegistry,
            MutableRegistry<Item> itemRegistry,
            MutableRegistry<Biome> biomeRegistry,
            MutableRegistry<Tag> tagRegistry,
            MutableRegistry<CreativeCategory> creativeCategoryRegistry
    ) {
        this.blockRegistry = Objects.requireNonNull(blockRegistry, "blockRegistry");
        this.itemRegistry = Objects.requireNonNull(itemRegistry, "itemRegistry");
        this.biomeRegistry = Objects.requireNonNull(biomeRegistry, "biomeRegistry");
        this.tagRegistry = Objects.requireNonNull(tagRegistry, "tagRegistry");
        this.creativeCategoryRegistry = Objects.requireNonNull(creativeCategoryRegistry, "creativeCategoryRegistry");
    }

    public void registry(String type, Function fn) {
        Objects.requireNonNull(type, "type");
        Objects.requireNonNull(fn, "fn");

        Context cx = Context.getCurrentContext();
        Scriptable scope = fn.getParentScope();

        switch (type) {
            case "block" -> {
                BlockRegistryEvent event = new BlockRegistryEvent();
                fn.call(cx, scope, scope, new Object[]{Context.javaToJS(event, scope)});
                for (BlockScriptBuilder builder : event.pending) {
                    blockRegistry.register(builder.id(), builder.build());
                    appendTags(builder.tags(), builder.id());
                }
            }
            case "item" -> {
                ItemRegistryEvent event = new ItemRegistryEvent();
                fn.call(cx, scope, scope, new Object[]{Context.javaToJS(event, scope)});
                for (ItemScriptBuilder builder : event.pending) {
                    itemRegistry.register(builder.id(), builder.build());
                    appendTags(builder.tags(), builder.id());
                }
            }
            case "biome" -> {
                BiomeRegistryEvent event = new BiomeRegistryEvent();
                fn.call(cx, scope, scope, new Object[]{Context.javaToJS(event, scope)});
                for (BiomeScriptBuilder builder : event.pending) {
                    biomeRegistry.register(builder.id(), builder.build());
                }
            }
            case "tag" -> {
                TagRegistryEvent event = new TagRegistryEvent();
                fn.call(cx, scope, scope, new Object[]{Context.javaToJS(event, scope)});
                for (TagScriptBuilder builder : event.pending) {
                    tagRegistry.register(builder.id(), builder.build());
                }
            }
            case "creative_category" -> {
                CreativeCategoryRegistryEvent event = new CreativeCategoryRegistryEvent();
                fn.call(cx, scope, scope, new Object[]{Context.javaToJS(event, scope)});
                for (CreativeCategoryScriptBuilder builder : event.pending) {
                    creativeCategoryRegistry.register(builder.id(), builder.build());
                }
            }
            default -> throw new IllegalArgumentException("Unknown registry type: " + type);
        }
    }

    private void appendTags(List<ResourceId> tagIds, ResourceId memberId) {
        for (ResourceId tagId : tagIds) {
            if (tagRegistry.contains(tagId)) {
                Tag existing = tagRegistry.require(tagId);
                if (!existing.members().contains(memberId)) {
                    Tag.Builder builder = Tag.builder().description(existing.description());
                    existing.members().forEach(builder::member);
                    builder.member(memberId);
                    tagRegistry.replace(tagId, builder.build());
                }
            } else {
                tagRegistry.register(tagId, Tag.builder()
                        .description("Generated by startup script")
                        .member(memberId)
                        .build());
            }
        }
    }

    public static final class BlockRegistryEvent {
        private final List<BlockScriptBuilder> pending = new ArrayList<>();

        public BlockScriptBuilder create(String id) {
            BlockScriptBuilder builder = new BlockScriptBuilder(ResourceId.id(Objects.requireNonNull(id, "id")));
            pending.add(builder);
            return builder;
        }
    }

    public static final class ItemRegistryEvent {
        private final List<ItemScriptBuilder> pending = new ArrayList<>();

        public ItemScriptBuilder create(String id) {
            ItemScriptBuilder builder = new ItemScriptBuilder(ResourceId.id(Objects.requireNonNull(id, "id")));
            pending.add(builder);
            return builder;
        }
    }

    public static final class BiomeRegistryEvent {
        private final List<BiomeScriptBuilder> pending = new ArrayList<>();

        public BiomeScriptBuilder create(String id) {
            BiomeScriptBuilder builder = new BiomeScriptBuilder(ResourceId.id(Objects.requireNonNull(id, "id")));
            pending.add(builder);
            return builder;
        }
    }

    public static final class TagRegistryEvent {
        private final List<TagScriptBuilder> pending = new ArrayList<>();

        public TagScriptBuilder create(String id) {
            TagScriptBuilder builder = new TagScriptBuilder(ResourceId.id(Objects.requireNonNull(id, "id")));
            pending.add(builder);
            return builder;
        }
    }

    public static final class CreativeCategoryRegistryEvent {
        private final List<CreativeCategoryScriptBuilder> pending = new ArrayList<>();

        public CreativeCategoryScriptBuilder create(String id) {
            CreativeCategoryScriptBuilder builder =
                    new CreativeCategoryScriptBuilder(ResourceId.id(Objects.requireNonNull(id, "id")));
            pending.add(builder);
            return builder;
        }
    }
}
