package com.terralite.game.scripting;

import com.terralite.core.registry.MutableRegistry;
import com.terralite.core.registry.ResourceId;
import com.terralite.game.biome.Biome;
import com.terralite.game.block.Block;
import com.terralite.game.category.CreativeCategory;
import com.terralite.game.item.Item;
import com.terralite.game.tag.Tag;
import org.mozilla.javascript.Context;
import org.mozilla.javascript.Function;
import org.mozilla.javascript.Scriptable;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public final class StartupEventsScriptApi {
    private final String namespace;
    private final MutableRegistry<Block> blockRegistry;
    private final MutableRegistry<Item> itemRegistry;
    private final MutableRegistry<Biome> biomeRegistry;
    private final MutableRegistry<Tag> tagRegistry;
    private final MutableRegistry<CreativeCategory> creativeCategoryRegistry;

    public StartupEventsScriptApi(
            String namespace,
            MutableRegistry<Block> blockRegistry,
            MutableRegistry<Item> itemRegistry,
            MutableRegistry<Biome> biomeRegistry,
            MutableRegistry<Tag> tagRegistry,
            MutableRegistry<CreativeCategory> creativeCategoryRegistry
    ) {
        this.namespace = Objects.requireNonNull(namespace, "namespace");
        this.blockRegistry = Objects.requireNonNull(blockRegistry, "blockRegistry");
        this.itemRegistry = Objects.requireNonNull(itemRegistry, "itemRegistry");
        this.biomeRegistry = Objects.requireNonNull(biomeRegistry, "biomeRegistry");
        this.tagRegistry = Objects.requireNonNull(tagRegistry, "tagRegistry");
        this.creativeCategoryRegistry = Objects.requireNonNull(creativeCategoryRegistry, "creativeCategoryRegistry");
    }

    public void registry(String type, Function fn) {
        Objects.requireNonNull(type, "type");
        Objects.requireNonNull(fn, "fn");

        Context cx = Context.getCurrentContext();
        Scriptable scope = fn.getParentScope();

        switch (type) {
            case "block" -> {
                BlockRegistryEvent event = new BlockRegistryEvent(namespace);
                fn.call(cx, scope, scope, new Object[]{Context.javaToJS(event, scope)});
                for (BlockScriptBuilder builder : event.pending) {
                    blockRegistry.register(builder.id(), builder.build());
                    appendTags(builder.tags(), builder.id());
                }
            }
            case "item" -> {
                ItemRegistryEvent event = new ItemRegistryEvent(namespace);
                fn.call(cx, scope, scope, new Object[]{Context.javaToJS(event, scope)});
                for (ItemScriptBuilder builder : event.pending) {
                    itemRegistry.register(builder.id(), builder.build());
                    appendTags(builder.tags(), builder.id());
                }
            }
            case "biome" -> {
                BiomeRegistryEvent event = new BiomeRegistryEvent(namespace);
                fn.call(cx, scope, scope, new Object[]{Context.javaToJS(event, scope)});
                for (BiomeScriptBuilder builder : event.pending) {
                    biomeRegistry.register(builder.id(), builder.build());
                }
            }
            case "tag" -> {
                TagRegistryEvent event = new TagRegistryEvent(namespace);
                fn.call(cx, scope, scope, new Object[]{Context.javaToJS(event, scope)});
                for (TagScriptBuilder builder : event.pending) {
                    tagRegistry.register(builder.id(), builder.build());
                }
            }
            case "creative_category" -> {
                CreativeCategoryRegistryEvent event = new CreativeCategoryRegistryEvent(namespace);
                fn.call(cx, scope, scope, new Object[]{Context.javaToJS(event, scope)});
                for (CreativeCategoryScriptBuilder builder : event.pending) {
                    creativeCategoryRegistry.register(builder.id(), builder.build());
                }
            }
            default -> throw new IllegalArgumentException("Unknown registry type: " + type);
        }
    }

    private void appendTags(List<ResourceId> tagIds, ResourceId memberId) {
        for (ResourceId tagId : tagIds) {
            if (tagRegistry.contains(tagId)) {
                Tag existing = tagRegistry.require(tagId);
                if (!existing.members().contains(memberId)) {
                    Tag.Builder builder = Tag.builder().description(existing.description());
                    existing.members().forEach(builder::member);
                    builder.member(memberId);
                    tagRegistry.replace(tagId, builder.build());
                }
            } else {
                tagRegistry.register(tagId, Tag.builder()
                        .description("Generated by startup script")
                        .member(memberId)
                        .build());
            }
        }
    }

    public static final class BlockRegistryEvent {
        private final String namespace;
        private final List<BlockScriptBuilder> pending = new ArrayList<>();

        BlockRegistryEvent(String namespace) {
            this.namespace = namespace;
        }

        public BlockScriptBuilder create(String id) {
            ResourceId resourceId = ResourceId.id(Objects.requireNonNull(id, "id"));
            requireOwnNamespace(resourceId, namespace);
            BlockScriptBuilder builder = new BlockScriptBuilder(resourceId);
            pending.add(builder);
            return builder;
        }
    }

    public static final class ItemRegistryEvent {
        private final String namespace;
        private final List<ItemScriptBuilder> pending = new ArrayList<>();

        ItemRegistryEvent(String namespace) {
            this.namespace = namespace;
        }

        public ItemScriptBuilder create(String id) {
            ResourceId resourceId = ResourceId.id(Objects.requireNonNull(id, "id"));
            requireOwnNamespace(resourceId, namespace);
            ItemScriptBuilder builder = new ItemScriptBuilder(resourceId);
            pending.add(builder);
            return builder;
        }
    }

    public static final class BiomeRegistryEvent {
        private final String namespace;
        private final List<BiomeScriptBuilder> pending = new ArrayList<>();

        BiomeRegistryEvent(String namespace) {
            this.namespace = namespace;
        }

        public BiomeScriptBuilder create(String id) {
            ResourceId resourceId = ResourceId.id(Objects.requireNonNull(id, "id"));
            requireOwnNamespace(resourceId, namespace);
            BiomeScriptBuilder builder = new BiomeScriptBuilder(resourceId);
            pending.add(builder);
            return builder;
        }
    }

    public static final class TagRegistryEvent {
        private final String namespace;
        private final List<TagScriptBuilder> pending = new ArrayList<>();

        TagRegistryEvent(String namespace) {
            this.namespace = namespace;
        }

        public TagScriptBuilder create(String id) {
            ResourceId resourceId = ResourceId.id(Objects.requireNonNull(id, "id"));
            requireOwnNamespace(resourceId, namespace);
            TagScriptBuilder builder = new TagScriptBuilder(resourceId);
            pending.add(builder);
            return builder;
        }
    }

    public static final class CreativeCategoryRegistryEvent {
        private final String namespace;
        private final List<CreativeCategoryScriptBuilder> pending = new ArrayList<>();

        CreativeCategoryRegistryEvent(String namespace) {
            this.namespace = namespace;
        }

        public CreativeCategoryScriptBuilder create(String id) {
            ResourceId resourceId = ResourceId.id(Objects.requireNonNull(id, "id"));
            requireOwnNamespace(resourceId, namespace);
            CreativeCategoryScriptBuilder builder = new CreativeCategoryScriptBuilder(resourceId);
            pending.add(builder);
            return builder;
        }
    }

    private static void requireOwnNamespace(ResourceId id, String namespace) {
        if (!id.namespace().equals(namespace)) {
            throw new IllegalArgumentException(
                "Pack '" + namespace + "' cannot register content under foreign namespace '" + id.namespace() + "'"
            );
        }
    }
}
