package com.terralite.tools.scripting;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public final class ScriptApiMarkdownGenerator {
    private ScriptApiMarkdownGenerator() {
    }

    public static void main(String[] args) throws IOException {
        Path workingDirectory = Path.of(System.getProperty("terralite.codegen.root", ""))
                .toAbsolutePath()
                .normalize();
        if (args.length > 0 && "--check".equals(args[0])) {
            Path output = args.length > 1
                    ? TypeScriptApiGenerator.resolveInsideWorkingDirectory(args[1], workingDirectory)
                    : workingDirectory.resolve("docs/scripting-api.md");
            check(output);
            return;
        }

        Path output = args.length > 0
                ? TypeScriptApiGenerator.resolveInsideWorkingDirectory(args[0], workingDirectory)
                : workingDirectory.resolve("build/generated/docs/scripting-api.md");
        generate(output);
    }

    public static void generate(Path output) throws IOException {
        Objects.requireNonNull(output, "output");
        Path parent = output.toAbsolutePath().normalize().getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        Files.writeString(output, markdown());
    }

    public static void check(Path output) throws IOException {
        Objects.requireNonNull(output, "output");
        String expected = markdown();
        String actual = Files.exists(output) ? Files.readString(output) : "";
        if (!expected.equals(actual)) {
            throw new IllegalStateException(
                    "Scripting API docs are stale. Run ./gradlew :tools:generateScriptingApiDocs "
                            + "(or .\\gradlew.bat :tools:generateScriptingApiDocs on Windows)"
            );
        }
    }

    static String markdown() {
        return render(ScriptApiSpec.create());
    }

    private static String render(ScriptApiSpec spec) {
        StringBuilder output = new StringBuilder()
                .append("# Terralite Scripting API\n\n")
                .append("Generated by `:tools:generateScriptingApiDocs` from the shared scripting API spec.\n\n")
                .append("## Globals\n\n");
        for (ScriptApiSpec.Global global : spec.globals()) {
            output.append("- `")
                    .append(global.name())
                    .append(": ")
                    .append(global.type())
                    .append("` - ")
                    .append(global.doc())
                    .append("\n");
        }

        output.append("\n## Types\n\n");
        for (ScriptApiSpec.TypeAlias alias : spec.aliases()) {
            output.append("### `")
                    .append(alias.name())
                    .append("`\n\n")
                    .append(alias.doc())
                    .append("\n\n")
                    .append("```ts\n")
                    .append("type ")
                    .append(alias.name())
                    .append(" = ")
                    .append(alias.value())
                    .append(";\n")
                    .append("```\n\n");
        }

        output.append("## Interfaces\n\n");
        for (ScriptApiSpec.Interface apiInterface : spec.interfaces()) {
            output.append("### `")
                    .append(apiInterface.name())
                    .append("`\n\n");
            appendMembers(output, apiInterface.members());
        }
        return output.toString();
    }

    private static void appendMembers(StringBuilder output, List<ScriptApiSpec.Member> members) {
        List<ScriptApiSpec.Method> methods = new ArrayList<>();
        List<ScriptApiSpec.Property> properties = new ArrayList<>();
        for (ScriptApiSpec.Member member : members) {
            if (member instanceof ScriptApiSpec.Method method) {
                methods.add(method);
            } else if (member instanceof ScriptApiSpec.Property property) {
                properties.add(property);
            } else {
                throw new IllegalArgumentException("Unsupported API member: " + member);
            }
        }

        if (!methods.isEmpty()) {
            output.append("#### Methods\n\n");
            for (ScriptApiSpec.Method method : methods) {
                output.append("- `")
                        .append(methodSignature(method))
                        .append("` - ")
                        .append(method.doc())
                        .append("\n");
            }
            output.append("\n");
        }

        if (!properties.isEmpty()) {
            output.append("#### Properties\n\n");
            for (ScriptApiSpec.Property property : properties) {
                output.append("- `")
                        .append(property.readonly() ? "readonly " : "")
                        .append(property.name())
                        .append(": ")
                        .append(property.type())
                        .append("` - ")
                        .append(property.doc())
                        .append("\n");
            }
            output.append("\n");
        }
    }

    private static String methodSignature(ScriptApiSpec.Method method) {
        List<String> renderedParams = new ArrayList<>();
        for (ScriptApiSpec.Param param : method.params()) {
            renderedParams.add(param.name() + ": " + param.type());
        }
        return method.name() + "(" + String.join(", ", renderedParams) + "): " + method.returnType();
    }
}
