package com.terralite.tools.scripting;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public final class TypeScriptApiGenerator {
    private TypeScriptApiGenerator() {
    }

    public static void main(String[] args) throws IOException {
        Path workingDirectory = Path.of(System.getProperty("terralite.codegen.root", ""))
                .toAbsolutePath()
                .normalize();
        if (args.length > 0 && "--check".equals(args[0])) {
            Path output = args.length > 1
                    ? resolveInsideWorkingDirectory(args[1], workingDirectory)
                    : workingDirectory.resolve("types/terralite-scripting.d.ts");
            check(output);
            return;
        }

        Path output = args.length > 0
                ? resolveInsideWorkingDirectory(args[0], workingDirectory)
                : workingDirectory.resolve("build/generated/types/terralite-scripting.d.ts");
        generate(output);
    }

    static Path resolveInsideWorkingDirectory(String path, Path workingDirectory) {
        Objects.requireNonNull(path, "path");
        Path normalizedRoot = Objects.requireNonNull(workingDirectory, "workingDirectory")
                .toAbsolutePath()
                .normalize();
        Path requested = Path.of(path);
        Path normalizedOutput = requested.isAbsolute()
                ? requested.normalize()
                : normalizedRoot.resolve(requested).normalize();
        if (!normalizedOutput.startsWith(normalizedRoot)) {
            throw new IllegalArgumentException("Output path must stay inside working directory: " + path);
        }
        return normalizedOutput;
    }

    public static void generate(Path output) throws IOException {
        Objects.requireNonNull(output, "output");
        Path parent = output.toAbsolutePath().normalize().getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        Files.writeString(output, declarations());
    }

    public static void check(Path output) throws IOException {
        Objects.requireNonNull(output, "output");
        String expected = declarations();
        String actual = Files.exists(output) ? Files.readString(output) : "";
        if (!expected.equals(actual)) {
            throw new IllegalStateException(
                    "TypeScript declarations are stale. Run ./gradlew :tools:generateTypeScriptApi "
                            + "(or .\\gradlew.bat :tools:generateTypeScriptApi on Windows)"
            );
        }
    }

    static String declarations() {
        return render(ScriptApiSpec.create());
    }

    private static String render(ScriptApiSpec spec) {
        StringBuilder output = new StringBuilder()
                .append("// Generated by :tools:generateTypeScriptApi.\n")
                .append("// Provides editor types for Terralite JavaScript content scripts.\n\n");
        for (ScriptApiSpec.TypeAlias alias : spec.aliases()) {
            output.append(topDoc(alias.doc()))
                    .append("type ")
                    .append(alias.name())
                    .append(" = ")
                    .append(alias.value())
                    .append(";\n\n");
        }
        for (ScriptApiSpec.Global global : spec.globals()) {
            output.append(topDoc(global.doc()))
                    .append("declare const ")
                    .append(global.name())
                    .append(": ")
                    .append(global.type())
                    .append(";\n\n");
        }
        for (ScriptApiSpec.Interface apiInterface : spec.interfaces()) {
            output.append(render(apiInterface)).append("\n");
        }
        return output.toString();
    }

    private static String render(ScriptApiSpec.Interface apiInterface) {
        StringBuilder output = new StringBuilder("interface ").append(apiInterface.name()).append(" {\n");
        for (ScriptApiSpec.Member member : apiInterface.members()) {
            output.append(render(member));
        }
        return output.append("}\n").toString();
    }

    private static String render(ScriptApiSpec.Member member) {
        if (member instanceof ScriptApiSpec.Method method) {
            List<String> renderedParams = new ArrayList<>();
            for (ScriptApiSpec.Param param : method.params()) {
                renderedParams.add(param.name() + ": " + param.type());
            }
            return "  /** " + method.doc() + " */\n"
                    + "  " + method.name() + "(" + String.join(", ", renderedParams) + "): "
                    + method.returnType() + ";\n";
        }
        if (member instanceof ScriptApiSpec.Property property) {
            return "  /** " + property.doc() + " */\n"
                    + "  " + (property.readonly() ? "readonly " : "") + property.name() + ": "
                    + property.type() + ";\n";
        }
        throw new IllegalArgumentException("Unsupported TypeScript member: " + member);
    }

    private static String topDoc(String doc) {
        return "/**\n * " + doc + "\n */\n";
    }
}
